# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
# Caching Dependencies - CircleCI https://circleci.com/docs/2.0/caching/
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5.6-node-browsers

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - dot-git-cache-{{ .Branch }}-{{ .Revision }}
            - dot-git-cache-{{ .Branch }}-
            - dot-git-cache-

      - checkout

      - run: php -v

      - save_cache:
          key: dot-git-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

  test:
    docker:
      - image: circleci/php:5.6-node-browsers

    working_directory: ~/repo

    steps:
      - run: ls -la ~/

  deploy:
    docker:
      - image: circleci/php:5.6-node-browsers

    working_directory: ~/repo

    steps:
      - run: php -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
          requires:
            - build
      - hold:
          type: approval
          requires:
           - test
      - deploy:
          requires:
            - hold
